### ISSUE TITLE
Please remove/hide this entry - thanks

### ISSUE THREAD

**Issue by gbtec-muhammedtoraman** [sthetix/DIAGRAM#11]

**Comment by sthetix** [comment]
I never tried using the hwfly-lite on the V2. The CPU QSB is it think
remain the same, you need to see the OLED diagram and apply it for the v2

**Comment by gbtec-muhammedtoraman** [comment]
@sthetix Please remove my comment and thx for the answere

**Comment by gbtec-muhammedtoraman** [comment]
please delete the entry completely - thanks
