### ISSUE TITLE
INSTINCT-NX V6S SWD POINTS

### ISSUE THREAD

**Issue by Idree** [sthetix/DIAGRAM#14]
Could you make a similar diagram of unbricking/flashing the instinct V6S chips using an ST-link?

I did find the one for the V6, but the chip lay-out is sadly completely different!

https://github.com/sthetix/DIAGRAM/blob/main/Instinct-NX-SWD-Points.jpg

**Comment by sthetix** [comment]
I will make the swd points for the v6s later

**Comment by Idree** [comment]
I was wondering if it's concerns the 5 test pads on the left.

I did some testing and it seems to be top to bottom.

3.3v.
N/A
GND
SWCLK
SWDIO

Is that correct?

**Comment by sthetix** [comment]
here it is

https://github.com/sthetix/DIAGRAM/raw/main/Instinct-NX-V6S-SWD-Points.jpg
